Devise
Bludidi/BlogApp pull request #19
Opened 2023-04-21 07:54 UTC by Bludidi

2023-04-21 08:53 UTC, VICTOR-CHUKWU requested changes
Hi @Bludidi  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 08:53 UTC, VICTOR-CHUKWU commented on db/migrate/20230420114025_add_unique_index_to_users_email.rb
> +end
- [ ] This is actually causing an error during migration kindly remove as email is already unique in the previous migration file

2023-04-21 08:53 UTC, VICTOR-CHUKWU commented on app/views/devise/sessions/new.html.erb
> +      <%= f.password_field :password, autocomplete: "current-password" %>
- [ ] after regristation i could not login in kindly check this [video](https://www.loom.com/share/1bc7e689f2934eb78c41f6123beed6d9) out

2023-04-22 05:38 UTC, jerryowusu approved these changes
Hi @Bludidi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![well done](https://user-images.githubusercontent.com/65233860/233765040-918c0c80-9b4f-4fef-8564-93a57f60ff36.gif)


## Highlights
:heavy_check_mark: Nice UI
:heavy_check_mark: Great effort in making the requested changes 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 05:40 UTC, merged